spring.application.name=jobportal
spring.datasource.url=jdbc:mysql://localhost:3306/jobportal


spring.datasource.username=root

spring.datasource.password=AT13052025

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
